USE [master]
GO

/****** Object:  Database [ExampleDB]    Script Date: 11/26/2012 1:51:41 PM ******/
CREATE DATABASE [ExampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExampleDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ExampleDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ExampleDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\ExampleDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ExampleDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExampleDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExampleDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExampleDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExampleDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExampleDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExampleDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ExampleDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ExampleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExampleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExampleDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExampleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExampleDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ExampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExampleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExampleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExampleDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ExampleDB] SET  MULTI_USER 
GO

ALTER DATABASE [ExampleDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExampleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExampleDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ExampleDB] SET  READ_WRITE 
GO


USE [ExampleDB]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 11/26/2012 1:54:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[CustomerID] [nvarchar](50) NOT NULL,
	[ContactName] [nvarchar](50) NOT NULL,
	[State] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL
) ON [PRIMARY]

GO

